---
driver:
  name: vagrant
  driver_config:
    require_chef_omnibus: latest

provisioner:
  name: chef_zero
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
- name: debian-7.6.0-amd64
  driver_config:
    box: debian-7.6.0-amd64
    box_url: https://vagrantcloud.com/ffuenf/boxes/debian-7.6.0-amd64/versions/8/providers/virtualbox.box

- name: ubuntu-14.04-server-amd64
  driver_config:
    box: ubuntu-14.04-server-amd64
    box_url: https://vagrantcloud.com/ffuenf/boxes/ubuntu-14.04-server-amd64/versions/11/providers/virtualbox.box

suites:
- name: default
  run_list:
    - recipe[modman::default]
  attributes: {}