language: ruby
bundler_args: --without kitchen_vagrant --without development
rvm:
- 2.1.5
- 2.2.0
script:
- bundle exec rubocop
- bundle exec foodcritic -f any .
notifications:
  slack:
    secure: WtVusuxDCJ+A5/CB/h4pHEZNdYQ4KxnJEgtxh6ZyadRg90Ege5rQkJDMTp+fXMusi1TSiPkgbQRC6TXVv+SPwwJau89hdV+6XIwzMhV+Y6rB6PWrFwdoIYAedfwbXWcNP+FeywQyRt/GbrLZjxSTctA8YYWh8fmGM7O2Ge58Wek=
